/* Browser smoke checks. See docs/redesign/VERIFICATION.md for setup. */
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { spawn } = require('node:child_process');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const root = path.resolve(__dirname, '..');
const base = process.env.SMOKE_BASE_URL || 'http://127.0.0.1:3000';
const screenshots = path.join(root, 'docs/redesign/screenshots');
let server;
async function startServer() {
  if (process.env.SMOKE_BASE_URL) return;
  server = spawn(process.execPath, ['node_modules/next/dist/bin/next', 'start', '--hostname', '127.0.0.1', '--port', '3000'], { cwd: path.join(root, 'frontend'), stdio: ['ignore', 'pipe', 'pipe'] });
  await new Promise((resolve, reject) => {
    server.stdout.on('data', b => { if (b.toString().includes('Ready')) resolve(); });
    server.stderr.on('data', b => process.stderr.write(b));
    server.on('error', reject);
    server.on('exit', c => reject(new Error(`Server exited: ${c}`)));
  });
}
(async () => {
  await startServer();
  const browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_EXECUTABLE ? { executablePath: process.env.CHROMIUM_EXECUTABLE } : {}), args: ['--no-sandbox'] });
  try {
    fs.mkdirSync(screenshots, { recursive: true });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
    const page = await context.newPage();
    const errors = []; const external = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('request', req => { if (!req.url().startsWith(base) && !req.url().startsWith('data:')) external.push(req.url()); });
    const go = async route => { await page.goto(base + route); await page.waitForTimeout(350); };
    const screenshot = async name => page.screenshot({ path: path.join(screenshots, name + '.png'), fullPage: true, animations: 'disabled' });
    const visible = async (selector, text) => { await page.locator(selector).filter({ hasText: text }).last().waitFor({ state: 'visible' }); };
    await go('/');
    await page.getByRole('button', { name: 'Enter workspace' }).click();
    await screenshot('01-workspace-desktop');
    const prompts = ['What is the capital gains tax for equity mutual funds?', 'Fee structure for Global Equity Fund', 'Are there any constraints for offshore trusts?'];
    for (const prompt of prompts) assert.equal(await page.getByText(prompt, { exact: true }).count(), 1);
    await page.getByText(prompts[0], { exact: true }).click();
    await visible('.thinking', 'Opening');
    await visible('.answer-card', 'Equity gains, clearly explained.');
    assert.ok(await page.getByText('₹9,375', { exact: false }).count());
    await screenshot('02-saved-answer');
    await page.locator('.citation-card').first().click();
    await page.getByRole('dialog').waitFor();
    const pdfLink = page.getByRole('link', { name: 'Open PDF · p. 20' });
    assert.equal(await pdfLink.getAttribute('href'), '/documents/capital-gains-guide.pdf#page=20');
    const pdf = await context.request.get(base + '/documents/capital-gains-guide.pdf');
    assert.equal(pdf.status(), 200); assert.ok((await pdf.body()).subarray(0, 4).toString() === '%PDF');
    await screenshot('03-evidence-drawer');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('dialog[open]').count(), 0);
    await page.getByRole('button', { name: 'Copy answer' }).click();
    assert.ok((await page.evaluate(() => navigator.clipboard.readText())).includes('PDF p. 20'));
    await page.getByRole('button', { name: 'Request specialist review' }).click();
    await visible('.toast', 'Saved');
    await page.getByRole('button', { name: 'Fee Structures', exact: true }).click();
    await visible('.answer-card', 'Start with the right share class.');
    assert.ok(!(await page.locator('.answer-card').last().textContent()).includes('1.50%'));
    await page.getByRole('button', { name: 'Compliance', exact: true }).click();
    await visible('.answer-card', 'A trust needs more than a yes or no.');
    await page.locator('.answer-card').last().locator('.citation-card').last().click();
    assert.equal(await page.getByRole('link', { name: 'Open PDF · p. 13' }).getAttribute('href'), '/documents/kyc-2023.pdf#page=13');
    await page.keyboard.press('Escape');
    await page.getByLabel('Ask a wealth advisory question').fill('An unsupported question');
    await page.getByRole('button', { name: 'Submit question' }).click();
    await visible('.answer-card', 'No saved answer');
    await page.getByRole('button', { name: 'Capital Gains Tax', exact: true }).click();
    await page.getByRole('button', { name: 'Stop response' }).click();
    await visible('.stopped', 'Response stopped');
    await page.getByRole('button', { name: 'Try again' }).click();
    await page.getByRole('button', { name: 'New', exact: true }).click();
    await page.waitForTimeout(2100);
    assert.equal(await page.locator('.answer-card').count(), 0);
    await go('/history');
    assert.ok(await page.locator('.history-row').count() >= 7);
    await page.getByLabel('Search conversations').fill('ISA');
    assert.equal(await page.locator('.history-row').count(), 1);
    await page.locator('.history-row').click();
    await visible('.answer-card', 'No saved answer');
    await go('/documents');
    assert.equal(await page.locator('.library-card').count(), 13);
    await screenshot('04-document-library');
    await page.getByRole('button', { name: 'Taxation', exact: true }).click();
    assert.equal(await page.locator('.library-card').count(), 2);
    await page.getByLabel('Search documents').fill('no-such-document');
    await visible('.empty-state', 'No documents found');
    await page.getByRole('button', { name: 'Reset filters' }).click();
    assert.equal(await page.locator('.library-card').count(), 13);
    await page.getByLabel('Sort documents').selectOption('name');
    await page.locator('.library-card').first().getByRole('button', { name: 'Read reference' }).click();
    await page.getByRole('button', { name: 'Show inline PDF preview' }).click();
    assert.equal(await page.locator('iframe').count(), 1);
    await page.keyboard.press('Escape');
    await go('/admin');
    await page.getByRole('button', { name: 'Review', exact: true }).first().click();
    assert.equal(await page.getByRole('button', { name: 'Save demo review' }).isDisabled(), true);
    await page.locator('.review-editor textarea').fill('Demo review: verify subsequent circulars before client use.');
    await page.getByRole('button', { name: 'Save demo review' }).click();
    await page.reload();
    await page.getByRole('button', { name: 'Reviewed in demo', exact: true }).click();
    assert.equal(await page.locator('.review-row').count(), 1);
    await screenshot('05-document-review');
    await go('/escalations');
    assert.equal(await page.locator('.escalation-card').count(), 3);
    assert.equal(await page.getByRole('button', { name: 'Resolve locally' }).first().isDisabled(), true);
    await page.locator('.escalation-card').first().locator('textarea').fill('Demo note: transaction date and tax year must be confirmed.');
    await page.getByRole('button', { name: 'Save draft' }).first().click();
    await page.reload();
    assert.ok((await page.locator('.escalation-card').first().locator('textarea').inputValue()).includes('tax year'));
    await page.getByRole('button', { name: 'Resolve locally' }).first().click();
    await page.getByRole('button', { name: 'Resolved', exact: true }).click();
    assert.equal(await page.locator('.escalation-card').count(), 1);
    await screenshot('06-specialist-review');
    // Mobile navigation and all route layouts, with fresh storage.
    const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' });
    const mobile = await mobileContext.newPage();
    mobile.on('pageerror', e => errors.push(e.message));
    for (const width of [390, 768, 1024, 320]) {
      await mobile.setViewportSize({ width, height: 844 });
      for (const route of ['/', '/documents', '/history', '/admin', '/escalations']) {
        await mobile.goto(base + route);
        assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `Horizontal overflow at ${width}px ${route}`);
      }
    }
    await mobile.setViewportSize({ width: 390, height: 844 }); await mobile.goto(base + '/');
    assert.equal(await mobile.locator('.intro').count(), 0);
    assert.equal(await mobile.locator('.sidebar').isVisible(), false);
    await mobile.screenshot({ path: path.join(screenshots, '07-workspace-mobile.png'), fullPage: true });
    await mobile.getByRole('button', { name: 'Open navigation' }).click();
    assert.equal(await mobile.locator('.sidebar').isVisible(), true);
    await mobile.getByRole('link', { name: 'Document library', exact: true }).click();
    assert.equal(await mobile.locator('.sidebar').isVisible(), false);
    await mobile.screenshot({ path: path.join(screenshots, '08-library-mobile.png'), fullPage: true });
    await mobile.goto(base + '/?q=' + encodeURIComponent(prompts[2]));
    await mobile.getByRole('heading', { name: 'A trust needs more than a yes or no.' }).waitFor();
    assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await mobile.screenshot({ path: path.join(screenshots, '09-answer-mobile.png'), fullPage: true });
    assert.deepEqual(errors, [], 'Browser errors');
    assert.deepEqual(external, [], 'Unexpected external network requests');
    console.log('PASS: original prompts; hardcoded answers; stop/reset; unsupported questions; copy; PDF pages; library search/filter; local history, reviews and escalations; 20 responsive route checks; reduced motion; mobile navigation. No browser errors or external requests.');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; }).finally(() => server?.kill());
